#
# Use Bash/PowerShell to debug buildspec commands. Substitute ${PWD} with $(pwd) if you're using Bash:
# docker run --tty -it -v ${PWD}:/project quay.io/quarkus/centos-quarkus-maven:20.2.0-java11 /bin/bash
#
version: 0.2
phases:
  build:
    commands:
      - export M2_HOME=~/.m2/repository
      - echo meta.build-number=$CODEBUILD_BUILD_NUMBER >> src/main/resources/application.properties
      - echo meta.source-version=$CODEBUILD_SOURCE_VERSION >> src/main/resources/application.properties
      - mvn -Pnative clean package -Dmaven.test.skip=true
artifacts:
  files:
    - function.zip
  base-directory: target
cache:
  paths:
    - '~/.m2/repository/**/*'
